### ISSUE TITLE
Can only VRM export Latifa and she has no data.

### ISSUE THREAD

**Issue by TwilightPrimus** [kitsune-ONE-team/KITSUNETSUKI-Asset-Tools#10]
I have tried to make the ini file a few ways and it still says that the file is missing. I made the file in the addon folder in blender and on the blend file itself. I can only get, as the title says, Latifa to export but she has no data. I am on the latest release of blender, 3.5. If more information is needed please let me know, not fully sure what else is required.
![textblock](https://user-images.githubusercontent.com/59343799/229670112-760e2750-2976-4aab-8b44-425c7448964d.png)

**Comment by TwilightPrimus** [comment]
Update: I can get up to exporting my model but he spazzes out, like he was exploding and I get the attached error message:

Python: Traceback (most recent call last):
  File "C:\Users\ancie\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\kitsunetsuki\exporter\vrm\__init__.py", line 377, in execute
    out, buf = e.convert()
  File "C:\Users\ancie\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\kitsunetsuki\exporter\vrm\__init__.py", line 285, in convert
    root, buffer_ = super().convert()
  File "C:\Users\ancie\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\kitsunetsuki\exporter\gltf\__init__.py", line 486, in convert
    root = super().convert()
  File "C:\Users\ancie\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\kitsunetsuki\exporter\base\__init__.py", line 231, in convert
    self.make_node(self._root)
  File "C:\Users\ancie\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\kitsunetsuki\exporter\base\__init__.py", line 193, in make_node
    self.make_node(node, child)
  File "C:\Users\ancie\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\kitsunetsuki\exporter\base\__init__.py", line 193, in make_node
    self.make_node(node, child)
  File "C:\Users\ancie\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\kitsunetsuki\exporter\base\__init__.py", line 193, in make_node
    self.make_node(node, child)
  File "C:\Users\ancie\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\kitsunetsuki\exporter\base\__init__.py", line 167, in make_node
    node = self.make_mesh(parent_node, obj)
  File "C:\Users\ancie\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\kitsunetsuki\exporter\gltf\__init__.py", line 450, in make_mesh
    self.make_geom(gltf_node, gltf_mesh, obj, can_merge=False)
  File "C:\Users\ancie\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\kitsunetsuki\exporter\gltf\geom.py", line 110, in make_geom
    apply_modifiers(obj, triangulate=triangulate)
  File "C:\Users\ancie\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\kitsunetsuki\base\objects.py", line 76, in apply_modifiers
    raise e
  File "C:\Users\ancie\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\kitsunetsuki\base\objects.py", line 69, in apply_modifiers
    bpy.ops.object.modifier_apply(modifier=mod.name)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Modifier is disabled, skipping apply

I can barley read it but I can see that at the end it talks about a disabled modifier, what does that mean?

**Comment by Yonnji** [comment]
>I have tried to make the ini file a few ways and it still says that the file is missing. I made the file in the addon folder in blender and on the blend file itself. 

You don't need to save it as file. Just keep it inside the Blender as text. You just need to rename the text block from "Text.001" to "VRM.ini". And looks like you already figured this out.

> RuntimeError: Error: Modifier is disabled, skipping apply
> I can barley read it but I can see that at the end it talks about a disabled modifier, what does that mean?

Modifier on some of the objects is disabled. If it needed then you should apply it manually.

It would be better to apply all the modifiers that you need and delete all modifiers that you don't need before exporting. Maybe some modifiers are breaking the model, so you would see at least which one.

This is modifiers tab with a single modifier as example:
![2023-04-05_13-05](https://user-images.githubusercontent.com/46163506/230049768-aa6c3df4-b9a7-467c-b32d-1e730701e63b.png)
