### ISSUE TITLE
(blender addon) Fails to export VRM blender 3.0

### ISSUE THREAD

**Issue by jurassicjordan** [kitsune-ONE-team/KITSUNETSUKI-Asset-Tools#5]
Python: Traceback (most recent call last):
  File "/home/jordancruz/.config/blender/3.0/scripts/addons/kitsunetsuki/exporter/vrm/__init__.py", line 350, in execute
    out, buf = e.convert()
  File "/home/jordancruz/.config/blender/3.0/scripts/addons/kitsunetsuki/exporter/vrm/__init__.py", line 258, in convert
    root, buffer_ = super().convert()
  File "/home/jordancruz/.config/blender/3.0/scripts/addons/kitsunetsuki/exporter/gltf/__init__.py", line 482, in convert
    root = super().convert()
  File "/home/jordancruz/.config/blender/3.0/scripts/addons/kitsunetsuki/exporter/base/__init__.py", line 186, in convert
    self._root = self.make_root_node()
  File "/home/jordancruz/.config/blender/3.0/scripts/addons/kitsunetsuki/exporter/vrm/__init__.py", line 76, in make_root_node
    'title': data['meta']['title'],
KeyError: 'meta'

location: <unknown location>:-1

**Comment by MarkMoonfang** [comment]
I can confirm the same issue.

![image](https://user-images.githubusercontent.com/103233332/162354425-c3bf14b7-148a-4127-945a-4882d3ed4794.png)

**Comment by Yonnji** [comment]
> KeyError: 'meta'

Solution - https://github.com/kitsune-ONE-team/KITSUNETSUKI-Asset-Tools/issues/2#issuecomment-1155210239

**Comment by Yonnji** [comment]
> I can confirm the same issue.

It's not the same problem. Some modifiers can't be applied. All modifiers are applied automatically during the export, but some of them fail for some reason. What modifiers do you have on this mesh?
