### ISSUE TITLE
RuntimeError: Error: Tangent space computation needs a UV Map, "UVMap" not found, aborting

### ISSUE THREAD

**Issue by adnanonline123** [kitsune-ONE-team/KITSUNETSUKI-Asset-Tools#9]
Python: Traceback (most recent call last):
  File "C:\Users\ADNAN 3D\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\kitsunetsuki\exporter\vrm\__init__.py", line 351, in execute
    out, buf = e.convert()
  File "C:\Users\ADNAN 3D\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\kitsunetsuki\exporter\vrm\__init__.py", line 259, in convert
    root, buffer_ = super().convert()
  File "C:\Users\ADNAN 3D\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\kitsunetsuki\exporter\gltf\__init__.py", line 489, in convert
    root = super().convert()
  File "C:\Users\ADNAN 3D\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\kitsunetsuki\exporter\base\__init__.py", line 231, in convert
    self.make_node(self._root)
  File "C:\Users\ADNAN 3D\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\kitsunetsuki\exporter\base\__init__.py", line 193, in make_node
    self.make_node(node, child)
  File "C:\Users\ADNAN 3D\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\kitsunetsuki\exporter\base\__init__.py", line 193, in make_node
    self.make_node(node, child)
  File "C:\Users\ADNAN 3D\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\kitsunetsuki\exporter\base\__init__.py", line 167, in make_node
    node = self.make_mesh(parent_node, obj)
  File "C:\Users\ADNAN 3D\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\kitsunetsuki\exporter\gltf\__init__.py", line 452, in make_mesh
    self.make_geom(gltf_node, gltf_mesh, obj, can_merge=False)
  File "C:\Users\ADNAN 3D\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\kitsunetsuki\exporter\gltf\geom.py", line 221, in make_geom
    uv_tb = self.get_tangent_bitangent(mesh)
  File "C:\Users\ADNAN 3D\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\kitsunetsuki\exporter\base\vertex.py", line 37, in get_tangent_bitangent
    mesh.calc_tangents(uvmap=uv_name)
RuntimeError: Error: Tangent space computation needs a UV Map, "UVMap" not found, aborting

**Comment by Yonnji** [comment]
Looks like you don't have any UV map on the model. Is it expected? Do you want to export without UV and textures?

**Comment by adnanonline123** [comment]
yes how to export without uv map?

**Comment by Yonnji** [comment]
It's not possible atm, but I will make a fix for that.
